/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/_admin'
import { Route as AuthenticatedAdminDashRouteImport } from './routes/_authenticated/_admin/dash'
import { Route as AuthJoinCodeIndexRouteImport } from './routes/auth/join.$code.index'
import { Route as AuthenticatedAdminAdminIndexRouteImport } from './routes/_authenticated/_admin/admin.index'
import { Route as AuthenticatedAdminAdminSiteNewRouteImport } from './routes/_authenticated/_admin/admin.site-new'
import { Route as AuthenticatedAdminAdminSiteSiteIndexRouteImport } from './routes/_authenticated/_admin/admin.site.$site.index'
import { Route as AuthenticatedAdminAdminSiteSiteUsersIndexRouteImport } from './routes/_authenticated/_admin/admin.site.$site.users.index'
import { Route as AuthenticatedAdminAdminSiteSiteInvitesIndexRouteImport } from './routes/_authenticated/_admin/admin.site.$site.invites.index'
import { Route as AuthenticatedAdminAdminSiteSiteFieldsIndexRouteImport } from './routes/_authenticated/_admin/admin.site.$site.fields.index'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminDashRoute = AuthenticatedAdminDashRouteImport.update({
  id: '/dash',
  path: '/dash',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthJoinCodeIndexRoute = AuthJoinCodeIndexRouteImport.update({
  id: '/auth/join/$code/',
  path: '/auth/join/$code/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminAdminIndexRoute =
  AuthenticatedAdminAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminSiteNewRoute =
  AuthenticatedAdminAdminSiteNewRouteImport.update({
    id: '/admin/site-new',
    path: '/admin/site-new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminSiteSiteIndexRoute =
  AuthenticatedAdminAdminSiteSiteIndexRouteImport.update({
    id: '/admin/site/$site/',
    path: '/admin/site/$site/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminSiteSiteUsersIndexRoute =
  AuthenticatedAdminAdminSiteSiteUsersIndexRouteImport.update({
    id: '/admin/site/$site/users/',
    path: '/admin/site/$site/users/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminSiteSiteInvitesIndexRoute =
  AuthenticatedAdminAdminSiteSiteInvitesIndexRouteImport.update({
    id: '/admin/site/$site/invites/',
    path: '/admin/site/$site/invites/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminSiteSiteFieldsIndexRoute =
  AuthenticatedAdminAdminSiteSiteFieldsIndexRouteImport.update({
    id: '/admin/site/$site/fields/',
    path: '/admin/site/$site/fields/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dash': typeof AuthenticatedAdminDashRoute
  '/admin/site-new': typeof AuthenticatedAdminAdminSiteNewRoute
  '/admin/': typeof AuthenticatedAdminAdminIndexRoute
  '/auth/join/$code/': typeof AuthJoinCodeIndexRoute
  '/admin/site/$site/': typeof AuthenticatedAdminAdminSiteSiteIndexRoute
  '/admin/site/$site/fields/': typeof AuthenticatedAdminAdminSiteSiteFieldsIndexRoute
  '/admin/site/$site/invites/': typeof AuthenticatedAdminAdminSiteSiteInvitesIndexRoute
  '/admin/site/$site/users/': typeof AuthenticatedAdminAdminSiteSiteUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dash': typeof AuthenticatedAdminDashRoute
  '/admin/site-new': typeof AuthenticatedAdminAdminSiteNewRoute
  '/admin': typeof AuthenticatedAdminAdminIndexRoute
  '/auth/join/$code': typeof AuthJoinCodeIndexRoute
  '/admin/site/$site': typeof AuthenticatedAdminAdminSiteSiteIndexRoute
  '/admin/site/$site/fields': typeof AuthenticatedAdminAdminSiteSiteFieldsIndexRoute
  '/admin/site/$site/invites': typeof AuthenticatedAdminAdminSiteSiteInvitesIndexRoute
  '/admin/site/$site/users': typeof AuthenticatedAdminAdminSiteSiteUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/_authenticated/_admin/dash': typeof AuthenticatedAdminDashRoute
  '/_authenticated/_admin/admin/site-new': typeof AuthenticatedAdminAdminSiteNewRoute
  '/_authenticated/_admin/admin/': typeof AuthenticatedAdminAdminIndexRoute
  '/auth/join/$code/': typeof AuthJoinCodeIndexRoute
  '/_authenticated/_admin/admin/site/$site/': typeof AuthenticatedAdminAdminSiteSiteIndexRoute
  '/_authenticated/_admin/admin/site/$site/fields/': typeof AuthenticatedAdminAdminSiteSiteFieldsIndexRoute
  '/_authenticated/_admin/admin/site/$site/invites/': typeof AuthenticatedAdminAdminSiteSiteInvitesIndexRoute
  '/_authenticated/_admin/admin/site/$site/users/': typeof AuthenticatedAdminAdminSiteSiteUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dash'
    | '/admin/site-new'
    | '/admin/'
    | '/auth/join/$code/'
    | '/admin/site/$site/'
    | '/admin/site/$site/fields/'
    | '/admin/site/$site/invites/'
    | '/admin/site/$site/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dash'
    | '/admin/site-new'
    | '/admin'
    | '/auth/join/$code'
    | '/admin/site/$site'
    | '/admin/site/$site/fields'
    | '/admin/site/$site/invites'
    | '/admin/site/$site/users'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/_admin'
    | '/_authenticated/dashboard'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/_authenticated/_admin/dash'
    | '/_authenticated/_admin/admin/site-new'
    | '/_authenticated/_admin/admin/'
    | '/auth/join/$code/'
    | '/_authenticated/_admin/admin/site/$site/'
    | '/_authenticated/_admin/admin/site/$site/fields/'
    | '/_authenticated/_admin/admin/site/$site/invites/'
    | '/_authenticated/_admin/admin/site/$site/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthJoinCodeIndexRoute: typeof AuthJoinCodeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin/dash': {
      id: '/_authenticated/_admin/dash'
      path: '/dash'
      fullPath: '/dash'
      preLoaderRoute: typeof AuthenticatedAdminDashRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/auth/join/$code/': {
      id: '/auth/join/$code/'
      path: '/auth/join/$code'
      fullPath: '/auth/join/$code/'
      preLoaderRoute: typeof AuthJoinCodeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin/admin/': {
      id: '/_authenticated/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/site-new': {
      id: '/_authenticated/_admin/admin/site-new'
      path: '/admin/site-new'
      fullPath: '/admin/site-new'
      preLoaderRoute: typeof AuthenticatedAdminAdminSiteNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/site/$site/': {
      id: '/_authenticated/_admin/admin/site/$site/'
      path: '/admin/site/$site'
      fullPath: '/admin/site/$site/'
      preLoaderRoute: typeof AuthenticatedAdminAdminSiteSiteIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/site/$site/users/': {
      id: '/_authenticated/_admin/admin/site/$site/users/'
      path: '/admin/site/$site/users'
      fullPath: '/admin/site/$site/users/'
      preLoaderRoute: typeof AuthenticatedAdminAdminSiteSiteUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/site/$site/invites/': {
      id: '/_authenticated/_admin/admin/site/$site/invites/'
      path: '/admin/site/$site/invites'
      fullPath: '/admin/site/$site/invites/'
      preLoaderRoute: typeof AuthenticatedAdminAdminSiteSiteInvitesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/site/$site/fields/': {
      id: '/_authenticated/_admin/admin/site/$site/fields/'
      path: '/admin/site/$site/fields'
      fullPath: '/admin/site/$site/fields/'
      preLoaderRoute: typeof AuthenticatedAdminAdminSiteSiteFieldsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminDashRoute: typeof AuthenticatedAdminDashRoute
  AuthenticatedAdminAdminSiteNewRoute: typeof AuthenticatedAdminAdminSiteNewRoute
  AuthenticatedAdminAdminIndexRoute: typeof AuthenticatedAdminAdminIndexRoute
  AuthenticatedAdminAdminSiteSiteIndexRoute: typeof AuthenticatedAdminAdminSiteSiteIndexRoute
  AuthenticatedAdminAdminSiteSiteFieldsIndexRoute: typeof AuthenticatedAdminAdminSiteSiteFieldsIndexRoute
  AuthenticatedAdminAdminSiteSiteInvitesIndexRoute: typeof AuthenticatedAdminAdminSiteSiteInvitesIndexRoute
  AuthenticatedAdminAdminSiteSiteUsersIndexRoute: typeof AuthenticatedAdminAdminSiteSiteUsersIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminDashRoute: AuthenticatedAdminDashRoute,
  AuthenticatedAdminAdminSiteNewRoute: AuthenticatedAdminAdminSiteNewRoute,
  AuthenticatedAdminAdminIndexRoute: AuthenticatedAdminAdminIndexRoute,
  AuthenticatedAdminAdminSiteSiteIndexRoute:
    AuthenticatedAdminAdminSiteSiteIndexRoute,
  AuthenticatedAdminAdminSiteSiteFieldsIndexRoute:
    AuthenticatedAdminAdminSiteSiteFieldsIndexRoute,
  AuthenticatedAdminAdminSiteSiteInvitesIndexRoute:
    AuthenticatedAdminAdminSiteSiteInvitesIndexRoute,
  AuthenticatedAdminAdminSiteSiteUsersIndexRoute:
    AuthenticatedAdminAdminSiteSiteUsersIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthJoinCodeIndexRoute: AuthJoinCodeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
