/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/_admin'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthJoinCodeIndexRouteImport } from './routes/auth/join.$code.index'
import { Route as AuthenticatedAdminAdminIndexRouteImport } from './routes/_authenticated/_admin/admin.index'
import { Route as AuthenticatedAdminAdminSiteNewRouteImport } from './routes/_authenticated/_admin/admin.site-new'
import { Route as AuthenticatedDashboardSSiteIndexRouteImport } from './routes/_authenticated/dashboard.s.$site.index'
import { Route as AuthenticatedAdminAdminSiteSiteIndexRouteImport } from './routes/_authenticated/_admin/admin.site.$site.index'
import { Route as AuthenticatedAdminAdminSiteSiteSettingsRouteImport } from './routes/_authenticated/_admin/admin.site.$site.settings'
import { Route as AuthenticatedAdminAdminSiteSiteUsersIndexRouteImport } from './routes/_authenticated/_admin/admin.site.$site.users.index'
import { Route as AuthenticatedAdminAdminSiteSiteInvitesIndexRouteImport } from './routes/_authenticated/_admin/admin.site.$site.invites.index'
import { Route as AuthenticatedAdminAdminSiteSiteFieldsIndexRouteImport } from './routes/_authenticated/_admin/admin.site.$site.fields.index'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_authenticated/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthJoinCodeIndexRoute = AuthJoinCodeIndexRouteImport.update({
  id: '/auth/join/$code/',
  path: '/auth/join/$code/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminAdminIndexRoute =
  AuthenticatedAdminAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminSiteNewRoute =
  AuthenticatedAdminAdminSiteNewRouteImport.update({
    id: '/admin/site-new',
    path: '/admin/site-new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedDashboardSSiteIndexRoute =
  AuthenticatedDashboardSSiteIndexRouteImport.update({
    id: '/_authenticated/dashboard/s/$site/',
    path: '/dashboard/s/$site/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminAdminSiteSiteIndexRoute =
  AuthenticatedAdminAdminSiteSiteIndexRouteImport.update({
    id: '/admin/site/$site/',
    path: '/admin/site/$site/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminSiteSiteSettingsRoute =
  AuthenticatedAdminAdminSiteSiteSettingsRouteImport.update({
    id: '/admin/site/$site/settings',
    path: '/admin/site/$site/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminSiteSiteUsersIndexRoute =
  AuthenticatedAdminAdminSiteSiteUsersIndexRouteImport.update({
    id: '/admin/site/$site/users/',
    path: '/admin/site/$site/users/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminSiteSiteInvitesIndexRoute =
  AuthenticatedAdminAdminSiteSiteInvitesIndexRouteImport.update({
    id: '/admin/site/$site/invites/',
    path: '/admin/site/$site/invites/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminSiteSiteFieldsIndexRoute =
  AuthenticatedAdminAdminSiteSiteFieldsIndexRouteImport.update({
    id: '/admin/site/$site/fields/',
    path: '/admin/site/$site/fields/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/site-new': typeof AuthenticatedAdminAdminSiteNewRoute
  '/admin/': typeof AuthenticatedAdminAdminIndexRoute
  '/auth/join/$code/': typeof AuthJoinCodeIndexRoute
  '/dashboard/s/$site/': typeof AuthenticatedDashboardSSiteIndexRoute
  '/admin/site/$site/settings': typeof AuthenticatedAdminAdminSiteSiteSettingsRoute
  '/admin/site/$site/': typeof AuthenticatedAdminAdminSiteSiteIndexRoute
  '/admin/site/$site/fields/': typeof AuthenticatedAdminAdminSiteSiteFieldsIndexRoute
  '/admin/site/$site/invites/': typeof AuthenticatedAdminAdminSiteSiteInvitesIndexRoute
  '/admin/site/$site/users/': typeof AuthenticatedAdminAdminSiteSiteUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/site-new': typeof AuthenticatedAdminAdminSiteNewRoute
  '/admin': typeof AuthenticatedAdminAdminIndexRoute
  '/auth/join/$code': typeof AuthJoinCodeIndexRoute
  '/dashboard/s/$site': typeof AuthenticatedDashboardSSiteIndexRoute
  '/admin/site/$site/settings': typeof AuthenticatedAdminAdminSiteSiteSettingsRoute
  '/admin/site/$site': typeof AuthenticatedAdminAdminSiteSiteIndexRoute
  '/admin/site/$site/fields': typeof AuthenticatedAdminAdminSiteSiteFieldsIndexRoute
  '/admin/site/$site/invites': typeof AuthenticatedAdminAdminSiteSiteInvitesIndexRoute
  '/admin/site/$site/users': typeof AuthenticatedAdminAdminSiteSiteUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authenticated/_admin/admin/site-new': typeof AuthenticatedAdminAdminSiteNewRoute
  '/_authenticated/_admin/admin/': typeof AuthenticatedAdminAdminIndexRoute
  '/auth/join/$code/': typeof AuthJoinCodeIndexRoute
  '/_authenticated/dashboard/s/$site/': typeof AuthenticatedDashboardSSiteIndexRoute
  '/_authenticated/_admin/admin/site/$site/settings': typeof AuthenticatedAdminAdminSiteSiteSettingsRoute
  '/_authenticated/_admin/admin/site/$site/': typeof AuthenticatedAdminAdminSiteSiteIndexRoute
  '/_authenticated/_admin/admin/site/$site/fields/': typeof AuthenticatedAdminAdminSiteSiteFieldsIndexRoute
  '/_authenticated/_admin/admin/site/$site/invites/': typeof AuthenticatedAdminAdminSiteSiteInvitesIndexRoute
  '/_authenticated/_admin/admin/site/$site/users/': typeof AuthenticatedAdminAdminSiteSiteUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/api/$'
    | '/auth/sign-in'
    | '/api/auth/$'
    | '/admin/site-new'
    | '/admin/'
    | '/auth/join/$code/'
    | '/dashboard/s/$site/'
    | '/admin/site/$site/settings'
    | '/admin/site/$site/'
    | '/admin/site/$site/fields/'
    | '/admin/site/$site/invites/'
    | '/admin/site/$site/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/api/$'
    | '/auth/sign-in'
    | '/api/auth/$'
    | '/admin/site-new'
    | '/admin'
    | '/auth/join/$code'
    | '/dashboard/s/$site'
    | '/admin/site/$site/settings'
    | '/admin/site/$site'
    | '/admin/site/$site/fields'
    | '/admin/site/$site/invites'
    | '/admin/site/$site/users'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/_authenticated/_admin'
    | '/api/$'
    | '/auth/sign-in'
    | '/api/auth/$'
    | '/_authenticated/_admin/admin/site-new'
    | '/_authenticated/_admin/admin/'
    | '/auth/join/$code/'
    | '/_authenticated/dashboard/s/$site/'
    | '/_authenticated/_admin/admin/site/$site/settings'
    | '/_authenticated/_admin/admin/site/$site/'
    | '/_authenticated/_admin/admin/site/$site/fields/'
    | '/_authenticated/_admin/admin/site/$site/invites/'
    | '/_authenticated/_admin/admin/site/$site/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  AuthSignInRoute: typeof AuthSignInRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  AuthJoinCodeIndexRoute: typeof AuthJoinCodeIndexRoute
  AuthenticatedDashboardSSiteIndexRoute: typeof AuthenticatedDashboardSSiteIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/join/$code/': {
      id: '/auth/join/$code/'
      path: '/auth/join/$code'
      fullPath: '/auth/join/$code/'
      preLoaderRoute: typeof AuthJoinCodeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin/admin/': {
      id: '/_authenticated/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/site-new': {
      id: '/_authenticated/_admin/admin/site-new'
      path: '/admin/site-new'
      fullPath: '/admin/site-new'
      preLoaderRoute: typeof AuthenticatedAdminAdminSiteNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/dashboard/s/$site/': {
      id: '/_authenticated/dashboard/s/$site/'
      path: '/dashboard/s/$site'
      fullPath: '/dashboard/s/$site/'
      preLoaderRoute: typeof AuthenticatedDashboardSSiteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin/admin/site/$site/': {
      id: '/_authenticated/_admin/admin/site/$site/'
      path: '/admin/site/$site'
      fullPath: '/admin/site/$site/'
      preLoaderRoute: typeof AuthenticatedAdminAdminSiteSiteIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/site/$site/settings': {
      id: '/_authenticated/_admin/admin/site/$site/settings'
      path: '/admin/site/$site/settings'
      fullPath: '/admin/site/$site/settings'
      preLoaderRoute: typeof AuthenticatedAdminAdminSiteSiteSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/site/$site/users/': {
      id: '/_authenticated/_admin/admin/site/$site/users/'
      path: '/admin/site/$site/users'
      fullPath: '/admin/site/$site/users/'
      preLoaderRoute: typeof AuthenticatedAdminAdminSiteSiteUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/site/$site/invites/': {
      id: '/_authenticated/_admin/admin/site/$site/invites/'
      path: '/admin/site/$site/invites'
      fullPath: '/admin/site/$site/invites/'
      preLoaderRoute: typeof AuthenticatedAdminAdminSiteSiteInvitesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/site/$site/fields/': {
      id: '/_authenticated/_admin/admin/site/$site/fields/'
      path: '/admin/site/$site/fields'
      fullPath: '/admin/site/$site/fields/'
      preLoaderRoute: typeof AuthenticatedAdminAdminSiteSiteFieldsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdminSiteNewRoute: typeof AuthenticatedAdminAdminSiteNewRoute
  AuthenticatedAdminAdminIndexRoute: typeof AuthenticatedAdminAdminIndexRoute
  AuthenticatedAdminAdminSiteSiteSettingsRoute: typeof AuthenticatedAdminAdminSiteSiteSettingsRoute
  AuthenticatedAdminAdminSiteSiteIndexRoute: typeof AuthenticatedAdminAdminSiteSiteIndexRoute
  AuthenticatedAdminAdminSiteSiteFieldsIndexRoute: typeof AuthenticatedAdminAdminSiteSiteFieldsIndexRoute
  AuthenticatedAdminAdminSiteSiteInvitesIndexRoute: typeof AuthenticatedAdminAdminSiteSiteInvitesIndexRoute
  AuthenticatedAdminAdminSiteSiteUsersIndexRoute: typeof AuthenticatedAdminAdminSiteSiteUsersIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdminSiteNewRoute: AuthenticatedAdminAdminSiteNewRoute,
  AuthenticatedAdminAdminIndexRoute: AuthenticatedAdminAdminIndexRoute,
  AuthenticatedAdminAdminSiteSiteSettingsRoute:
    AuthenticatedAdminAdminSiteSiteSettingsRoute,
  AuthenticatedAdminAdminSiteSiteIndexRoute:
    AuthenticatedAdminAdminSiteSiteIndexRoute,
  AuthenticatedAdminAdminSiteSiteFieldsIndexRoute:
    AuthenticatedAdminAdminSiteSiteFieldsIndexRoute,
  AuthenticatedAdminAdminSiteSiteInvitesIndexRoute:
    AuthenticatedAdminAdminSiteSiteInvitesIndexRoute,
  AuthenticatedAdminAdminSiteSiteUsersIndexRoute:
    AuthenticatedAdminAdminSiteSiteUsersIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  AuthSignInRoute: AuthSignInRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  AuthJoinCodeIndexRoute: AuthJoinCodeIndexRoute,
  AuthenticatedDashboardSSiteIndexRoute: AuthenticatedDashboardSSiteIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
